# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:  
  #- group: ade-variables  
  LOCATION: "westeurope"
  AZURE_RESOURCE_GROUP: "ade-rg1"
  AZURE_DEVCENTER: "devbox001"
  AZURE_PROJECT: ""
  AZURE_KEYVAULT: ""
  CATALOG_REPO: 'https://dev.azure.com/damayantib/customerpoc/_git/ade-demo'
  PAT: ""

  
pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'masterconnection'
    KeyVaultName: 'pocmasterkeyvault'
    SecretsFilter: 'adopat'
    RunAsPreJob: true
- task: AzureCLI@2
  displayName: Configure Dev Center and its components
  inputs:
    azureSubscription: 'masterconnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |    
      
      
      #Get the deploying users id for RBAC assignments
      #DEPLOYINGUSERID=$(az ad signed-in-user show --query id -o tsv)
      DEPLOYINGUSERID='0afc90a4-ea9c-422b-bace-b313bf20953b'
            
      #Create resource group
      az group create -n $AZURE_RESOURCE_GROUP -l westeurope
      
      #Deploy the common infrastructure
      DEVCENTERNAME=$(az deployment group create -g $AZURE_RESOURCE_GROUP -f ADE-Config/bicep/common.bicep -p nameseed=$AZURE_DEVCENTER devboxProjectUser=$DEPLOYINGUSERID --query 'properties.outputs.devcenterName.value' -o tsv)
      
      #Deploy Microsoft Dev Box Infrastructure
      #az deployment group create -g $RG -f ADE-Config/bicep/devbox.bicep -p devcenterName=$DCNAME
      
      #Configure and Deploy Microsoft Dev Box Infrastructure      
      # PAT='https://abndevcenterkeyvault.vault.azure.net/secrets/adopat'
      
      az deployment group create -g $AZURE_RESOURCE_GROUP -f ADE-Config/bicep/ade.bicep -p devcenterName=$DEVCENTERNAME catalogRepoUri=$CATALOG_REPO catalogRepoPat=$adopat adeProjectUser=$DEPLOYINGUSERID
      
      AZURE_DEVCENTER_PRINCIPAL_ID=$(az resource list -n $DEVCENTERNAME --query [*].identity.principalId --out tsv)
      AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

      az role assignment create \
        --scope /subscriptions/$AZURE_SUBSCRIPTION_ID \
        --role Owner \
        --assignee-object-id $AZURE_DEVCENTER_PRINCIPAL_ID \
        --assignee-principal-type ServicePrincipal

      # DEVUSER=user@contoso.com
      # DEVUSERID=$(az ad user show --id $DEVUSER --query id -o tsv)
      # SUBID=$(az account show --query id -o tsv)
      # PROJECTNAME=developers
      # PROJECTID=/subscriptions/$SUBID/resourceGroups/$RG/providers/Microsoft.DevCenter/projects/$PROJECTNAME

      #Dev box
      # az role assignment create --assignee $DEVUSER --role "DevCenter Dev Box User" --scope $PROJECTID
